config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'homes/about' => 'homes#about', as: :about
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :users, :except => [:destroy, :new]
  get 'users/:id/confirm' => 'users#confirm', as: :confirm
  patch 'users/:id/withdrawal' => 'users#withdrawal', as: :withdrawal
  resources :arts do
    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
  end
  resources :exhibitions
  get 'exhibitions/:id/thanks' => 'exhibitions#thanks', as: :thanks
  delete 'cart_arts/empty' => 'cart_arts#empty', as: :empty
  resources :cart_arts, only: [:create, :destroy]
  resources :exhibition_arts, only: [:show, :create, :destroy ]
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/exhibition.rb
class Exhibition < ApplicationRecord
  belongs_to :user
  has_many :exhibition_arts, dependent: :destroy

  validates :title, presence: true, length: {maximum: 20 }
  validates :detail, presence: true, length: {maximum: 50 }
  validate :start_date_check
  validate :end_date_check
  validate :date_count

  def start_date_check
    errors.add(:start_date, "は現在時刻以降のものを選択してください") if start_date < DateTime.now.in_time_zone('Tokyo')
  end

  def end_date_check
    errors.add(:end_date, "は開始日以降のものを選択してください") if end_date < start_date
  end

  def date_count
    errors.add(:end_date, "開催期間は5日間以内に設定してください") if end_date - start_date > self.second(5)
  end

  def second(date) #秒数を日数に変換
    date * 24 * 60 * 60
  end

  def new_exhibition(user, parameter)
    Exhibition.transaction do
      self.save!
      user.cart_arts.each do |cart_art|
        exhibition_art = self.exhibition_arts.new(art_id: cart_art.art.id)
        exhibition_art.save
      end
      event = user.events.new(parameter)
      event.event_type = 2
      event.exhibition_id = self.id
      event.save!
      user.cart_arts.destroy_all
    end
  end

end

app/controllers/exhibitions_controller.rb
class ExhibitionsController < ApplicationController
  require 'date'
  before_action :authenticate_user!, :except => [:index, :show]
  before_action :correct_data, only: [:show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :set_exhibition, only: [:show, :edit, :destroy, :update]
  before_action :period_checker, only: [:create, :new]

  def index
    @exhibitions = Exhibition.all
  end

  def new
    if current_user.cart_arts.empty?
      redirect_to user_path(current_user), notice: 'イラストが選択されていません。詳細ページより選択してください。'
    end
    @exhibition = Exhibition.new
    @cart_arts = CartArt.where(user_id: current_user.id)
  end

  def create
    @exhibition = current_user.exhibitions.new(exhibition_params)
    @exhibition.new_exhibition(current_user, exhibition_params) #exhibition.rb参照
      redirect_to thanks_path(@exhibition)
    rescue => e #transactionが失敗した時の処理
      @cart_arts = CartArt.where(user_id: current_user.id)
      render :new
  end

  def show
    @exhibition = Exhibition.find(params[:id])
    @comment = Comment.new
  end

  def update
    if @exhibition.update(exhibition_params)
      event = Event.where(exhibition_id: @exhibition.id)
      event.update(exhibition_params)
      redirect_to exhibition_path(@exhibition)
    else
      render :edit
    end
  end

  def destroy
    event = Event.find_by(exhibition_id: @exhibition.id)
    if @exhibition.destroy #同時にイベントを削除
      event.destroy
    end
    redirect_to exhibitions_path
  end

  private
  def exhibition_params
    params.require(:exhibition).permit(:title, :detail, :start_date, :end_date)
  end

  def set_exhibition
    @exhibition = Exhibition.find(params[:id])
  end

  def correct_data #存在しないデータへのアクセス防止
    @exhibition = Exhibition.find_by_id(params[:id])
    if @exhibition.nil?
      redirect_to exhibitions_path, notice: 'お探しのページは表示できません。'
    end
  end

  def correct_user #URL直打ち防止
    @exhibition = Exhibition.find_by_id(params[:id])
    if @exhibition.nil? || @exhibition.user_id != current_user.id
      redirect_to exhibitions_path, notice: 'お探しのページは表示できません。'
    end
  end

  def period_checker #展覧会の重複開催防止。直近のend_dateより現在が過去の場合、展覧会の新規作成はできない。
    exhibition = current_user.exhibitions.maximum(:end_date)
    if exhibition.nil? == false and exhibition > DateTime.now.in_time_zone('Tokyo')
      redirect_to user_path(current_user), notice: '既存の展覧会が終了後、新規展覧会を作成できます。'
    end
  end
end

app/helpers/exhibitions_helper.rb
module ExhibitionsHelper
end

app/views/exhibitions/edit.html.erb
<div class="container">
  <h4 class="title">Edit Exhibition</h4>
  <div class="row">
    <div class="exhibition-edit-form">
      <%= form_with model: @exhibition, url: exhibition_path(@exhibition), method: :patch, local: true do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>

        <div class="col-xs-3 col-xs-offset-1">
          <%= f.label :title %>
          <%= f.text_field :title %><br>

          <%= f.label :detail %><br>
          <%= f.text_area :detail %><br>
        </div>

        <div class="col-xs-8">
          <%= f.label :start_date %>
          <%= f.datetime_select :start_date, {default: DateTime.now.in_time_zone('Tokyo')} %><br>

          <%= f.label :end_date %>
          <%= f.datetime_select :end_date, {default: DateTime.now.in_time_zone('Tokyo')} %><br><br><br>

          <%= f.submit '編集する', class: 'btn btn-default' %>
          <%= link_to '展覧会を削除する', exhibition_path(@exhibition), method: :delete,"data-confirm" => "本当に削除しますか？", class: 'btn btn-default' %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="exhibition-edit-form-art">
      <div class="row">
        <div class="exhibition-art">
          <p>現在選択中のイラスト</p>
          <% @exhibition.exhibition_arts.each do |exhibition_art| %>
            <div class="col-xs-3">
              <%= attachment_image_tag exhibition_art.art, :image, :fill, 100, 100, format: 'jpeg' %>
              <h4><%= exhibition_art.art.title %></h4>
              <%= link_to '作品を削除する', exhibition_art_path(exhibition_art), method: :delete, class: 'btn btn-default' %><br>
            </div>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="exhibition-art-add">
          <p>イラストの追加は以下から</p>
          <%= form_with model: @exhibition, url: exhibition_arts_path, method: :post, local: true do |f| %>
            <%= f.collection_check_boxes(:exhibition_art_ids, current_user.arts, :id, :title) do |t| %>
              <% unless @exhibition.exhibition_arts.where(art_id: t.object.id ).exists? %>
                <% t.label do %>
                  <%= t.check_box :checked => false %>
                  <%= attachment_image_tag t.object, :image, :fill, 100, 100, format: 'jpeg' %><br>
                <% end %>
              <% end %>
            <% end %>
            <%= hidden_field_tag :id, @exhibition.id %><br>
            <%= f.submit '追加する', class: 'btn btn-default' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/exhibitions/index.html.erb
<div class="container">
  <% if flash[:notice] %>
    <div class="flash">
      <%= flash[:notice] %>
    </div>
  <% end %>
  <div class="row">
    <div class="exhibition-container">
      <h4 class="title">Exhibitions</h4>
      <table class="exhibition-index">
        <thead>
          <tr>
            <th>Title</th>
            <th>Detail</th>
            <th>Presenter</th>
            <th></th>
            <th colspan="4"></th>
          </tr>
        </thead>
        <tbody>
          <% @exhibitions.each do |exhibition| %>
            <% if (exhibition.start_date..exhibition.end_date).cover?(DateTime.now.in_time_zone('Tokyo')) %>
              <tr>
                <td><h6 class="count"><%= link_to exhibition.title, exhibition_path(exhibition) %></h6></td>
                <td><%= exhibition.detail %></td>
                <td><%= exhibition.user.name %></td>
                <td>
                  <% if user_signed_in? && exhibition.user == current_user %>
                    <%= link_to '展覧会を削除する', exhibition_path(exhibition), method: :delete,"data-confirm" => "本当に削除しますか？", class: 'btn btn-default' %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
      <h3 class="message"></h3>
    </div>
  </div>
</div>

app/views/exhibitions/new.html.erb
<div class="container">
  <% if flash[:notice] %>
    <div class="flash">
      <%= flash[:notice] %>
    </div>
  <% end %>
  <div class="row">
    <h4 class="title">New Exhibition</h4>
    <div class="cart-art-form">
      <div class="row">
        <% @cart_arts.each do |cart_art| %>
          <div class="col-xs-3">
            <%= attachment_image_tag cart_art.art, :image, :fill, 100, 100, format: 'jpeg' %><br>
            <%= cart_art.art.title %>
            <%= link_to '取り消す', cart_art_path(cart_art),method: :delete, class: 'btn btn-default' %>
          </div>
        <% end %>
      </div>
      <div class="row">
        <%= link_to '全て選びなおす', empty_path, method: :delete, class: 'btn btn-default' %>
        <%= link_to '追加する', arts_path(user_id: current_user.id), class: 'btn btn-default' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="exhibition-form">
      <%= form_with model: @exhibition, url: exhibitions_path, method: :post, local: true do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
        <div class="col-xs-3 col-xs-offset-1">
          <%= f.label :title %>
          <%= f.text_field :title %><br>

          <%= f.label :detail %><br>
          <%= f.text_area :detail %>
        </div>
        <div class="col-xs-8">
          <%= f.label :start_date %>
          <%= f.datetime_select :start_date, {default: DateTime.now.in_time_zone('Tokyo')} %><br>

          <%= f.label :end_date %>
          <%= f.datetime_select :end_date, {default: DateTime.now.in_time_zone('Tokyo')} %><br><br><br><br>

          <%= f.submit '展覧会を作成する', class: 'btn btn-default' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/exhibitions/show.html.erb
<% if (@exhibition.start_date..@exhibition.end_date).cover?(DateTime.now.in_time_zone('Tokyo')) || @exhibition.user == current_user %>
  <div class="container">
    <div class="exhibition-show-container">
      <div class=" exhibition-title">
          <h3><%= @exhibition.title %>presented by <%= @exhibition.user.name %></h3>
          <%= link_to user_path(@exhibition.user) do %>
            <%= attachment_image_tag @exhibition.user, :profile_image, :fill, 90, 90, format: 'jpeg', class: ' exhibition-user-image'  %>
          <% end %>
          <p><%= @exhibition.detail %></p>
          <% if user_signed_in? && @exhibition.user == current_user && @exhibition.end_date > DateTime.now.in_time_zone('Tokyo') %>
            <%= link_to '編集する', edit_exhibition_path(@exhibition), class: 'btn btn-default' %>
          <% end %>
      </div>
      <div class="row">
        <div class="exhibition-show">
          <div class="col-xs-12">
            <% @exhibition.exhibition_arts.each do |exhibition_art| %>
              <div class="col-xs-4 modal-container">
                <div class="modal-contents">
                  <div class="js-modal-btn">
                    <%= attachment_image_tag exhibition_art.art, :image, :fill, 200, 200, format: 'jpeg', class: 'art-image' %>
                  </div>
                  <h4><%= exhibition_art.art.title %></h4>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% @exhibition.exhibition_arts.each do |exhibition_art| %><!-- モーダルウィンドウ表示用 -->
    <div class="modal js-modal">
      <div class="modal-bg js-modal-close"></div>
      <div class="modal-content">
        <%= render 'arts/art', art: exhibition_art.art, comment: @comment %>
        <p class="js-modal-close">Close</p>
      </div>
    </div>
  <% end %>
<% else %>
  <h6>展覧会は終了しました</h6>
<% end %>

app/views/exhibitions/thanks.html.erb
<div class="container">
  <div class="row">
    <div class="thanks">
      <h4>Thanks!</h4>
      <p>展覧会の受付が完了しました。</p>
    </div>
  </div>
</div>