config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'homes/about' => 'homes#about', as: :about
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :users, :except => [:destroy, :new]
  get 'users/:id/confirm' => 'users#confirm', as: :confirm
  patch 'users/:id/withdrawal' => 'users#withdrawal', as: :withdrawal
  resources :arts do
    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
  end
  resources :exhibitions
  get 'exhibitions/:id/thanks' => 'exhibitions#thanks', as: :thanks
  delete 'cart_arts/empty' => 'cart_arts#empty', as: :empty
  resources :cart_arts, only: [:create, :destroy]
  resources :exhibition_arts, only: [:show, :create, :destroy ]
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :arts, dependent: :destroy
  has_many :exhibitions, dependent: :destroy
  has_many :cart_arts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :events, dependent: :destroy

  attachment :profile_image

  validates :name, presence: true, length: {maximum: 10}, format: { with: /\A[a-z0-9]+\z/ }
  validates :introduction, length: {maximum: 30}

  def add_art?(art_id) #current_userが選択済みのartかどうか判別
    self.cart_arts.where(art_id: art_id).exists?
  end

  def active_for_authentication? #退会済みユーザーの判定に使用
    self.is_deleted == "有効"
  end

  enum user_status: {
    閲覧のみ: 0,
    投稿機能あり: 1
  }

  enum is_deleted: {
    退会済み: true,
    有効: false
  }
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :reject_user, only: [:create]
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def reject_user #退会済みユーザーをはじく。
    user = User.find_by(email: params[:user][:email].downcase) #emailからユーザーを特定
    if user
      if (user.valid_password?(params[:user][:password]) && (user.active_for_authentication? == false)) #user.rb参照
        flash[:error] = '退会済みユーザーです。'
        redirect_to new_user_session_path
      end
    else
      flash[:error] = "必須項目を入力してください。"
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  require 'date'
  before_action :authenticate_user!, :except => [:index, :show]
  before_action :correct_data, only: [:show]
  before_action :correct_user, only: [:edit, :update, :confirm, :withdrawal]
  def index
    @users = User.page(params[:page]).reverse_order
  end

  def show
    @user = User.find(params[:id])
    @arts = @user.arts.page(params[:page]).reverse_order
    @exhibitions = @user.exhibitions.page(params[:page]).reverse_order
    if user_signed_in?
      @events = Event.where(user_id: current_user.id)
    end
    @event = Event.new
  end

  def update
    if current_user.update(user_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def withdrawal #退会機能
    current_user.update(is_deleted:true)
    reset_session #ログアウト
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def correct_data #存在しないデータへのアクセス防止
    @user = User.find_by_id(params[:id])
    if @user.nil?
      redirect_to users_path, notice: 'お探しのページは表示できません。'
    end
  end

  def correct_user #URL直打ち防止
    @user = User.find_by_id(params[:id])
    if @user.nil? || @user.id != current_user.id
      redirect_to users_path, notice: 'お探しのページは表示できません。'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_template.html.erb
<div class="profile-container">
  <div class="profile-image-window">
    <%= attachment_image_tag user, :profile_image, :fill, 90, 90, format: 'jpeg', fallback: "no-image.jpeg", class: 'profile-image' %>
    <div class="user-info">
      <h3><%= user.name %></h3><br>
    </div>
  </div>
  <div class="introduction">
    <p><%= user.name %>'s comment</p>
    <p><%= user.introduction %></p><br>
  </div>
  <% if user == current_user %>
    <%= link_to new_art_path do %>
      <span class="glyphicon glyphicon-pencil btn btn-default" aria-hidden="true">投稿する</span>
    <% end %>
    <%= link_to edit_user_path(user) do %>
      <span class="glyphicon glyphicon-wrench btn btn-default" aria-hidden="true">編集する</span>
    <% end %>
    <div id="calendar"></div>
    <%= link_to '予定を入力する', new_event_path, class: 'btn btn-default' %>
  <% end %>
</div>

app/views/users/confirm.html.erb
<div class="container">
  <% if flash[:notice] %>
    <div class="flash">
      <%= flash[:notice] %>
    </div>
  <% end %>
  <div class="row">
    <div class="confirm-container">
      <h3 class="title">退会確認画面</h3>
      <p>本当に退会しますか？</p>
      <p>退会するとログインできなくなります。</p>
      <%= link_to '退会しない', user_path(current_user), class: 'btn btn-default' %>
      <%= link_to '退会する', withdrawal_path(current_user), method: :patch, class: 'btn btn-default' %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="edit-user-form">
      <h4 class="title">Edit info</h4>
      <%= form_with model: current_user, url: user_path(current_user), method: :patch, local: true do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>

      <div class="row">
        <div class="edit-user-image">
          <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, size: "100x100", fallback: 'no-image.jpg',  onClick: "$('.image_field').click()", class: 'image_prev' %><br>
          <%= f.file_field :profile_image, class: 'image_field edit-image' %>
        </div>
      </div>

      <div class="row">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>

      <div class="row">
        <%= f.label :introduction %>
        <%= f.text_area :introduction %>
      </div>

      <div class="row">
        <%= f.submit '更新する', class: 'btn btn-default' %>
        <%= link_to '退会する', confirm_path(current_user), class: 'btn btn-default' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <% if flash[:notice] %>
    <div class="flash">
      <%= flash[:notice] %>
    </div>
  <% end %>
  <div class="row">
    <h4 class="title">Artists index</h4>
    <div class="user-container">
      <% @users.each do |user| %>
        <div class="user-index">
          <%= attachment_image_tag user, :profile_image, :fill, 100, 100, size: "100x100", format: 'jpeg', fallback: 'no-image.jpeg', class: 'profile-image' %>
          <h3 class="user-index-name"><%= link_to user.name, user_path(user) %></h3>
        </div>
      <% end %>
      <%= paginate @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <% if flash[:notice] %>
    <div class="flash">
      <%= flash[:notice] %>
    </div>
  <% end %>
  <div class="row">
    <div class="col-xs-3">
      <%= render 'users/template', user: @user %>
    </div>
    <div class="col-xs-9">
      <div class="col-xs-7">
        <h3 class="topic"><%= @user.name %>'s Arts</h3>
        <% @arts.each do |art| %>
          <div class="col-xs-4 user-art">
            <%= link_to art_path(art) do %>
              <%= attachment_image_tag art, :image, :fill, 100, 100, format: 'jpeg', class: 'art-image' %><br>
            <% end %>
            <h4 class="art-title"><%= link_to art.title, art_path(art) %></h4><br>
          </div>
        <% end %>
        <%= paginate @arts %>
      </div>
      <% if user_signed_in? && @user == current_user %>
        <div class="col-xs-5">
          <h3 class="topic"><%= @user.name %>'s Exhibitions</h3>
          <div class="user-exhibition-title">
            <%= link_to '新規展覧会作成', new_exhibition_path, class: 'btn btn-default' %><br>
            <% @exhibitions.each do |exhibition| %>
                <%= link_to exhibition.title, exhibition_path(exhibition), class: 'exhibition-link' %><br>
                <% if exhibition.end_date > DateTime.now.in_time_zone('Tokyo') %>
                  <%= link_to '↑この展覧会を編集する', edit_exhibition_path(exhibition), class: 'btn btn-default' %><br>
                <% end %>
            <% end %>
            <%= paginate @exhibitions %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>