config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'homes/about' => 'homes#about', as: :about
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :users, :except => [:destroy, :new]
  get 'users/:id/confirm' => 'users#confirm', as: :confirm
  patch 'users/:id/withdrawal' => 'users#withdrawal', as: :withdrawal
  resources :arts do
    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
  end
  resources :exhibitions
  get 'exhibitions/:id/thanks' => 'exhibitions#thanks', as: :thanks
  delete 'cart_arts/empty' => 'cart_arts#empty', as: :empty
  resources :cart_arts, only: [:create, :destroy]
  resources :exhibition_arts, only: [:show, :create, :destroy ]
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true


end

app/models/art.rb
class Art < ApplicationRecord
  belongs_to :user
  has_many :exhibition_arts, dependent: :destroy
  has_many :cart_arts, dependent: :destroy
  has_many :art_tags, dependent: :destroy
  has_many :tags, through: :art_tags
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  attachment :image

  validates :title, presence: true, length: {maximum: 10}
  validates :detail, presence: true, length: {maximum: 20}
  validates :image, presence: true

  def liked_by?(user) #引数userがいいねをしているかどうか
    likes.where(user_id: user.id).exists?
  end
end

app/models/art_tag.rb
class ArtTag < ApplicationRecord
  belongs_to :art
  belongs_to :tag
end

app/models/cart_art.rb
class CartArt < ApplicationRecord
  belongs_to :user
  belongs_to :art
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :art

  validates :comment, presence: true, length: {maximum: 30}
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: {maximum: 10}
  validates :detail, presence: true, length: {maximum: 20}
  validate :end_date_check

  def end_date_check
   errors.add(:end_date, "は開始日以降のものを選択してください") if end_date < start_date
  end

  enum event_type: {
    プライベート: 0,
    イラスト投稿日: 1,
    展覧会: 2
  }
end

app/models/exhibition.rb
class Exhibition < ApplicationRecord
  belongs_to :user
  has_many :exhibition_arts, dependent: :destroy

  validates :title, presence: true, length: {maximum: 20 }
  validates :detail, presence: true, length: {maximum: 50 }
  validate :start_date_check
  validate :end_date_check
  validate :date_count

  def start_date_check
    errors.add(:start_date, "は現在時刻以降のものを選択してください") if start_date < DateTime.now.in_time_zone('Tokyo')
  end

  def end_date_check
    errors.add(:end_date, "は開始日以降のものを選択してください") if end_date < start_date
  end

  def date_count
    errors.add(:end_date, "開催期間は5日間以内に設定してください") if end_date - start_date > self.second(5)
  end

  def second(date) #秒数を日数に変換
    date * 24 * 60 * 60
  end

  def new_exhibition(user, parameter)
    Exhibition.transaction do
      self.save!
      user.cart_arts.each do |cart_art|
        exhibition_art = self.exhibition_arts.new(art_id: cart_art.art.id)
        exhibition_art.save
      end
      event = user.events.new(parameter)
      event.event_type = 2
      event.exhibition_id = self.id
      event.save!
      user.cart_arts.destroy_all
    end
  end

end

app/models/exhibition_art.rb
class ExhibitionArt < ApplicationRecord
  belongs_to :exhibition
  belongs_to :art
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :art
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :art_tags, dependent: :destroy
  has_many :arts, through: :art_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :arts, dependent: :destroy
  has_many :exhibitions, dependent: :destroy
  has_many :cart_arts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :events, dependent: :destroy

  attachment :profile_image

  validates :name, presence: true, length: {maximum: 10}, format: { with: /\A[a-z0-9]+\z/ }
  validates :introduction, length: {maximum: 30}

  def add_art?(art_id) #current_userが選択済みのartかどうか判別
    self.cart_arts.where(art_id: art_id).exists?
  end

  def active_for_authentication? #退会済みユーザーの判定に使用
    self.is_deleted == "有効"
  end

  enum user_status: {
    閲覧のみ: 0,
    投稿機能あり: 1
  }

  enum is_deleted: {
    退会済み: true,
    有効: false
  }
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/helpers/cart_arts_helper.rb
module CartArtsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/exhibitions_helper.rb
module ExhibitionsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="about-header">
      <%= image_tag 'wart-logo-6.png', alt: 'LOGO', size: '400*200', class: 'about-logo' %>
      <h3 class="about-title">What's Wart?</h3>
    </div>
  </div>
  <div class="row">
    <div class="navgation">
      <div class="col-xs-6 nav-title">
        <p>このサイトについて</p>
      </div>
      <div class="col-xs-6">
        <div class="nav-text">
          <p>このサイトはイラストが好きな人のための投稿サイトです。</p><br>
          <p>自分の描いたイラストを投稿したり、他の人が描いたイラストを見ることができます。</p><br>
          <p>サイトに登録するといいねやコメントはもちろん、個人の展覧会を開くことができます。</p>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="concept">
      <div class="col-xs-6">
        <div class="concept-text">
          <p>落ち着いてイラスト鑑賞を行えるように控えめな配色にしました。</p><br>
          <p>コメントを通して交流していただければと思います。</p><br>
          <p>様々なイラストと出会ってください。</p><br>
        </div>
      </div>
      <div class="col-xs-6 concept-title">
        <p>コンセプト紹介</p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="about-exhibition">
      <div class="col-xs-6 about-exhibition-title">
        <p>展覧会について</p>
      </div>
      <div class="col-xs-6">
        <div class="about-exhibition-text">
          <p>このサイトではオンラインで展覧会を開くことができます。</p><br>
          <p>展覧会は最大で5日間開催することができます。</p><br>
          <p>開催中の展覧会は<%= link_to 'こちら', exhibitions_path %>から確認することができます。</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <% if flash[:notice] %>
    <div class="flash">
      <%= flash[:notice] %>
    </div>
  <% end %>
  <div class="row">
    <div class="top-logo">
      <%= image_tag 'wart-logo-6.png', alt: 'LOGO', class: 'top-logo', size: '400*200' %>
    </div>
  </div>
  <div class="row">
    <div class="top-text">
      <p>ようこそWartへ</p><br>
      <p>このサイトはイラスト好きのためのイラスト投稿サイトです</p><br>
      <p>たくさんのイラストを楽しみましょう</p><br>
      <p>まずは<%= link_to "What's Wart?", about_path %>ページをご覧ください。</p>
    </div>
  </div>
  <div class="row">
    <div class="top-menu">
      <div class="top-btns-1">
        <%= link_to "What's Wart?", about_path, class: 'top-btn' %>
        <%= link_to 'Arts', arts_path, class: 'top-btn' %>
      </div>
      <div class="top-btns-2">
        <%= link_to 'Exhibitions', exhibitions_path, class: 'top-btn' %>
        <%= link_to 'Artists', users_path, class: 'top-btn' %>
      </div>
    </div>
  </div>
</div>